[package]
name = "calendar"
version = "0.1.0"
authors = ["Makich Karagezyan <mak.kar@mail.ru>"]
edition = "2018"

[lib]
name = "calendar"
crate-type = ["rlib", "dylib"] 

[dependencies]
chrono = "0.4.6"